name:                shuffle
version:             0.1.0.0
github:              "DCPagan/shuffle"
license:             BSD-2-Clause
author:              "D.C. Pagan"
maintainer:          "dcpagan@posteo.net"
copyright:           "2023 D.C. Pagan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DCPagan/shuffle#readme>

dependencies:
- base >= 4.7 && < 5
- random
- text
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-type-defaults
- -XTupleSections

library:
  source-dirs: src

executables:
  shuf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shuffle

tests:
  shuffle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shuffle
